import type { AnalysisResult } from "../bindings/AnalysisResult";
import type { TrackedPr } from "../bindings/TrackedPr";
import { FIT_LABEL } from "../components/analysis/AssessmentView";
import { IMPACT_LABEL, PILLAR_LABEL } from "./comments";

/** The assessment as a Markdown document — what the Assessment tab shows,
 *  in the same order, plus the review plan and the run's metrics — so it
 *  pastes whole into a PR comment, a Teams message, or a doc. The reader
 *  has none of the app's context, so every section is self-labelled and
 *  nothing depends on colour or layout. */
export function assessmentMarkdown(pr: TrackedPr, result: AnalysisResult): string {
  const a = result.assessment;
  const out: string[] = [];
  const line = (...parts: string[]) => out.push(...parts);

  line(`# ${pr.repo} #${pr.number}: ${pr.title}`, "");
  line(
    `${pr.url} · by @${pr.author} · head \`${result.headSha.slice(0, 7)}\` · analyzed ${formatWhen(result.createdAt)}`,
    "",
  );

  line("## Summary", "", a.summary, "");
  if (a.detail.trim()) line(a.detail.trim(), "");
  line(`**Fit:** ${a.fit} — ${FIT_LABEL[a.fit]}`, "");
  if (a.fitRationale.trim()) line(a.fitRationale.trim(), "");

  if (a.contextNotes.length > 0) {
    line("## What you'd need to know without full context", "");
    for (const n of a.contextNotes) line(`- ${n}`);
    line("");
  }

  if (a.boundaryImpacts.length > 0) {
    line("## Boundary impacts", "", "Most important first.", "");
    a.boundaryImpacts.forEach((b, i) => line(`${i + 1}. **${IMPACT_LABEL[b.kind]}** — ${b.description}`));
    line("");
  }

  line("## Code findings", "");
  if (result.codePass?.startsWith("failed")) {
    line(`_The code-level pass failed (${result.codePass}); this section may be missing findings._`, "");
  }
  if (result.codeFindings.length === 0) {
    line(result.codePass === "off" ? "_Code pass off._" : "None.", "");
  } else {
    const byFile = new Map<string, typeof result.codeFindings>();
    for (const f of result.codeFindings) byFile.set(f.path, [...(byFile.get(f.path) ?? []), f]);
    for (const [path, findings] of byFile) {
      line(`### \`${path}\``, "");
      for (const f of findings) {
        const where = f.line != null ? `line ${f.line}: ` : "";
        line(`- **${f.severity} · ${f.kind}** — ${where}${f.finding}`, `  - Fix: ${f.suggestion}`);
      }
      line("");
    }
  }

  if (a.wellArchitected.length > 0) {
    line("## Well-Architected findings", "");
    const byPillar = new Map<string, typeof a.wellArchitected>();
    for (const f of a.wellArchitected) {
      const key = PILLAR_LABEL[f.pillar];
      byPillar.set(key, [...(byPillar.get(key) ?? []), f]);
    }
    for (const [pillar, findings] of byPillar) {
      line(`### ${pillar}`, "");
      for (const f of findings) line(`- **${f.severity}** — ${f.finding}`, `  - Recommendation: ${f.recommendation}`);
      line("");
    }
  }

  if (a.reviewPlan.length > 0) {
    line("## Review plan", "", "| File | Significance | Why |", "| --- | --- | --- |");
    for (const p of a.reviewPlan) line(`| \`${p.path}\` | ${p.significance} | ${cell(p.reason)} |`);
    line("");
  }

  const u = result.usage;
  const rows: [string, string][] = [
    ["Level", `${result.level}${result.focusNodeId ? ` (drilled into ${result.focusNodeId})` : ""}`],
    ["Effort", u.effort ?? "model default"],
    ["Time to process", u.elapsedMs > 0 ? formatDuration(u.elapsedMs) : "—"],
    ["Turns", String(u.turns)],
    ["Tokens in (uncached)", u.inputTokens.toLocaleString()],
    ["Cache read", u.cacheReadTokens.toLocaleString()],
    ["Cache written", u.cacheWriteTokens.toLocaleString()],
    ["Prompt total", (u.inputTokens + u.cacheReadTokens + u.cacheWriteTokens).toLocaleString()],
    ["Tokens out", u.outputTokens.toLocaleString()],
    ["Diff", `${pr.changedFiles} files · +${pr.additions} −${pr.deletions}`],
    ["Code pass", result.codePass ?? "—"],
  ];
  line("## Analysis metrics", "", "| Metric | Value |", "| --- | --- |");
  for (const [k, v] of rows) line(`| ${k} | ${v} |`);
  line("", "_Generated by CORA._");

  return out.join("\n");
}

/** A table cell can't hold a pipe or a line break. */
function cell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " ");
}

function formatDuration(ms: number): string {
  const s = Math.round(ms / 1000);
  return s < 60 ? `${s}s` : `${Math.floor(s / 60)}m ${s % 60}s`;
}

function formatWhen(iso: string): string {
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? iso : d.toLocaleString();
}
