// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the callout's activity feed: something happened on a PR the
 * reviewer cares about. Written by the poller as it detects changes;
 * read/flag state is the reviewer's own.
 */
export type ActivityItem = { id: number, at: string, prId: string, repo: string, number: number, prTitle: string, 
/**
 * comment | review | commits | ci | merged | closed | reopened | new | ready
 */
kind: string, 
/**
 * GitHub login behind the event, when known ("" otherwise).
 */
actor: string, 
/**
 * Human line for the feed, e.g. `responded: "looks good but…"`.
 */
summary: string, 
/**
 * Comment to deep-link to, when the event is a comment.
 */
commentId: string, 
/**
 * Authored-by-me PRs and high-priority repos/PRs are always important.
 */
important: boolean, read: boolean, 
/**
 * "" | "must-review" | "follow-up"
 */
flag: string, };
