// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything in Settings that shapes what an analysis produces. Not the
 * credentials, not the polling — the parts an experiment varies.
 */
export type AiConfig = { bedrockModelId: string, bedrockDrillModelId: string, bedrockChatModelId: string, bedrockScoutModelId: string, bedrockEffortArch: string, bedrockEffortDrill: string, bedrockEffortCode: string, archMaxOutputTokens: number, codeMaxOutputTokens: number, routeRoutinePrsToDrillModel: boolean, codeFindingsPass: boolean, customSystemPrompt: string, reviewConventions: string, };
