// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisLevel } from "./AnalysisLevel";

/**
 * Streaming progress for the UI ("reading src/payments/…").
 */
export type AnalysisProgress = { prId: string, level: AnalysisLevel, 
/**
 * Drill focus node id; empty for the root run. Lets the UI key
 * concurrent runs of the same level precisely.
 */
focus: string, message: string, };
