// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisLevel } from "./AnalysisLevel";
import type { Assessment } from "./Assessment";
import type { C4Graph } from "./C4Graph";

export type AnalysisResult = { prId: string, headSha: string, level: AnalysisLevel, 
/**
 * For Component/Code levels: the node the user drilled into.
 */
focusNodeId: string | null, graph: C4Graph, assessment: Assessment, createdAt: string, };
