// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisLevel } from "./AnalysisLevel";

/**
 * The assessment as it streams out of the write-up turn — the summary and
 * detail written so far, so the reader gets the verdict while the graph is
 * still being generated.
 */
export type AnalysisDraft = { prId: string, level: AnalysisLevel, focus: string, summary: string | null, detail: string | null, };
