// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisErrorKind } from "./AnalysisErrorKind";
import type { AnalysisLevel } from "./AnalysisLevel";

export type AnalysisError = { prId: string, level: AnalysisLevel, 
/**
 * Drill focus node id; empty for the root run.
 */
focus: string, error: string, kind: AnalysisErrorKind, };
