// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token cost of one analysis run.
 */
export type AnalysisUsage = { inputTokens: number, outputTokens: number, turns: number, 
/**
 * Prompt tokens served from the cache — the reason `input_tokens` can
 * read as a few dozen on a run that sent hundreds of thousands: Bedrock
 * reports only the uncached remainder there. Zero on runs before this
 * was recorded.
 */
cacheReadTokens: number, 
/**
 * Prompt tokens written into the cache this run.
 */
cacheWriteTokens: number, 
/**
 * Wall-clock time of the architecture pass, kickoff to submission.
 */
elapsedMs: number, 
/**
 * The effort level the run was sent with; None when the model's own
 * default applied. Kept so runs at different levels can be compared.
 */
effort: string | null, };
