// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisLevel } from "./AnalysisLevel";
import type { AnalysisUsage } from "./AnalysisUsage";
import type { Assessment } from "./Assessment";
import type { C4Graph } from "./C4Graph";
import type { CodeFinding } from "./CodeFinding";
import type { TraceStep } from "./TraceStep";

export type AnalysisResult = { prId: string, headSha: string, level: AnalysisLevel, 
/**
 * For Component/Code levels: the node the user drilled into.
 */
focusNodeId: string | null, graph: C4Graph, assessment: Assessment, createdAt: string, 
/**
 * The agent's exploration steps, for re-reading after the fact.
 */
trace: Array<TraceStep>, usage: AnalysisUsage, 
/**
 * Second-stage line-anchored findings (context level only).
 */
codeFindings: Array<CodeFinding>, 
/**
 * How the code pass ended: "ok" | "failed: <reason>" | "off". None on
 * analyses that predate the field or on drilled levels — an empty
 * findings list is only trustworthy when this says "ok".
 */
codePass: string | null, };
