// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse failure classes the UI can build recovery flows around.
 */
export type AnalysisErrorKind = "aws-auth" | "github-auth" | "other";
