// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoundaryImpact } from "./BoundaryImpact";
import type { FitVerdict } from "./FitVerdict";
import type { ReviewPlanEntry } from "./ReviewPlanEntry";
import type { WaFinding } from "./WaFinding";

export type Assessment = { 
/**
 * The TLDR — at most two short sentences.
 */
summary: string, 
/**
 * The fuller explanation, shown behind a "more detail" expander.
 */
detail: string, fit: FitVerdict, 
/**
 * Defaults tolerate models that omit "empty" fields despite the schema.
 */
fitRationale: string, 
/**
 * Ordered most-important-first; external impacts always lead.
 */
boundaryImpacts: Array<BoundaryImpact>, wellArchitected: Array<WaFinding>, 
/**
 * What a reviewer without full context needs to know.
 */
contextNotes: Array<string>, 
/**
 * Per-changed-file attention guidance, most important first.
 */
reviewPlan: Array<ReviewPlanEntry>, };
