// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One user-taken action, recorded for the History view. `old_value` is what
 * undo restores.
 */
export type AuditEntry = { id: number, at: string, 
/**
 * muted | unmuted | untracked | tracked | pr-priority | repo-priority
 */
action: string, subjectId: string, 
/**
 * Human-readable subject ("owner/repo#123 — title" or "owner/repo").
 */
subjectLabel: string, oldValue: string, newValue: string, undone: boolean, };
