// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImpactKind } from "./ImpactKind";

export type BoundaryImpact = { kind: ImpactKind, description: string, nodeIds: Array<string>, };
