// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which build this is. Answers the question a version number can't: the
 * binary in front of you says 0.1.0 whether it came from `tauri dev` five
 * minutes ago or a bundle from July.
 */
export type BuildInfo = { 
/**
 * From Cargo.toml — shared with tauri.conf.json's bundle version.
 */
version: string, 
/**
 * "dev" for a debug build (what `npm run tauri dev` produces, serving
 * the frontend from the Vite dev server), "release" for a bundle.
 */
profile: string, 
/**
 * Short commit the binary was compiled from, or "unknown" outside a
 * git checkout.
 */
commit: string, 
/**
 * Branch at compile time, or "detached". Meaningful mostly for dev
 * builds, where it says which line of work is actually running.
 */
branch: string, 
/**
 * Tracked files were modified when this was compiled — so the commit
 * identifies the base, not the exact source.
 */
dirty: boolean, 
/**
 * Compile time, RFC 3339 UTC. The one field that separates two dev
 * builds of the same dirty tree.
 */
builtAt: string, 
/**
 * The whole thing on one line, formatted once here so the UI and any
 * future log line or bug report can't drift into two conventions:
 * `0.1.0 · dev · main a1b2c3d*`, asterisk meaning a dirty tree, as in
 * a shell prompt.
 */
label: string, };
