// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { C4Edge } from "./C4Edge";
import type { C4Node } from "./C4Node";

export type C4Graph = { nodes: Array<C4Node>, edges: Array<C4Edge>, };
