// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatItemKind } from "./ChatItemKind";

/**
 * One entry in the assistant conversation transcript.
 */
export type ChatItem = { at: string, kind: ChatItemKind, text: string, };
