// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatUsage } from "./ChatUsage";
import type { ContextPart } from "./ContextPart";

/**
 * Everything the assistant will see on its next turn, itemised.
 */
export type ChatContext = { modelId: string, parts: Array<ContextPart>, 
/**
 * Best answer to "what will the next request carry": the raw estimate
 * scaled by how far it missed on the last measured request.
 */
projectedTokens: number, 
/**
 * The uncalibrated ~4-chars-per-token sum of `parts`.
 */
estTokens: number, 
/**
 * The model's context window, 0 when we don't know it for this id.
 */
windowTokens: number, 
/**
 * Measured cost of the most recent request, when one has been made.
 */
usage: ChatUsage | null, 
/**
 * Requests made in this session (a turn with tool calls makes several).
 */
requests: number, };
