// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatItem } from "./ChatItem";
import type { ChatPendingAction } from "./ChatPendingAction";

/**
 * Snapshot of a PR's chat session for (re)mounting the panel.
 */
export type ChatTranscript = { items: Array<ChatItem>, busy: boolean, pending: ChatPendingAction | null, };
