// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A mutating app action the assistant wants to take — held until the user
 * confirms, so every outward effect stays a human decision.
 */
export type ChatPendingAction = { name: string, 
/**
 * One-line human description ("comment on src/api.ts:41").
 */
summary: string, 
/**
 * The full text/body the action would post, for review before running.
 */
detail: string, };
