// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatItem } from "./ChatItem";
import type { ChatPendingAction } from "./ChatPendingAction";

/**
 * Payload for chat:item / chat:state events.
 */
export type ChatEvent = { prId: string, item: ChatItem | null, busy: boolean, pending: ChatPendingAction | null, };
