// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the last request to the model actually cost, straight from Bedrock.
 */
export type ChatUsage = { 
/**
 * The whole prompt Bedrock counted: `input_tokens` plus both cache
 * buckets. This is "how big is the context", and the number to
 * calibrate estimates against.
 */
promptTokens: number, 
/**
 * Billed at full rate — the part of the prompt the cache did NOT serve.
 * On a warm cache this is a handful of tokens, not the context size.
 */
inputTokens: number, outputTokens: number, 
/**
 * Prefix served from the prompt cache — in context, but cheap.
 */
cacheReadTokens: number, cacheWriteTokens: number, };
