// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What class of code-level finding the second pass reports.
 */
export type CodeFindingKind = "defect" | "reuse" | "convention";
