// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeFindingKind } from "./CodeFindingKind";
import type { Severity } from "./Severity";

/**
 * Line-anchored output of the code-findings pass — the altitude below the
 * architecture assessment, still above style nits.
 */
export type CodeFinding = { path: string, 
/**
 * New-side diff line the finding anchors to, when the model gave one.
 */
line: number | null, severity: Severity, kind: CodeFindingKind, finding: string, suggestion: string, };
