// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextGroup } from "./ContextGroup";

/**
 * One labelled slice of the model's context, with the exact text that
 * occupies it. Nothing here is a summary — `text` is what gets sent.
 */
export type ContextPart = { id: string, group: ContextGroup, 
/**
 * Human label: "PR facts", "call get_file", "get_file → src/api.ts".
 */
label: string, 
/**
 * Where the bytes came from: repo file, github, analysis, you, model…
 */
origin: string, 
/**
 * Estimated tokens (~4 chars each). The real count for the whole
 * request is in `usage` — only Bedrock can give an exact number.
 */
estTokens: number, 
/**
 * The verbatim text. Empty when the caller asked for sizes only.
 */
text: string, };
