// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a slice of context sits in the request the model receives.
 */
export type ContextGroup = "system" | "tools" | "messages";
