// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Objective, language-agnostic signals computed from a file's patch.
 * These ground the model's per-file significance calls (and let us catch
 * a "critical" tag on a file whose additions contain no actual logic).
 */
export type FileMetrics = { additions: number, deletions: number, 
/**
 * Branch points introduced by added lines (if/loops/boolean ops) —
 * a cyclomatic-complexity-delta proxy.
 */
addedBranches: number, 
/**
 * Function/class/type definitions introduced by added lines.
 */
newDefs: number, 
/**
 * Share of added lines that are imports/includes, 0..1.
 */
importShare: number, 
/**
 * Deepest indentation level (~4 columns per level) among added lines.
 */
maxNesting: number, };
