// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A GitHub org (or the viewer's personal account) the PAT can see.
 */
export type GithubOrg = { login: string, name: string, 
/**
 * True for the viewer's own account row.
 */
personal: boolean, };
