// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Priority order the whole product is built around:
 * external systems > service boundaries > internal modules.
 */
export type ImpactKind = "external" | "service" | "internal";
