// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";

export type LogEntry = { at: string, level: LogLevel, 
/**
 * Subsystem: poller | github | bedrock | analysis | app
 */
source: string, message: string, };
