// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Assistant-initiated viewed-marking. The frontend owns diff parsing and
 * per-file digests, so Rust only announces intent and the UI applies it
 * through the same path as a manual checkbox.
 */
export type MarkViewedEvent = { prId: string, 
/**
 * Ignored when `all` is set.
 */
paths: Array<string>, all: boolean, viewed: boolean, };
