// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one model id costs, in dollars per million tokens.
 */
export type ModelPrice = { 
/**
 * Exact model id or ARN as configured — matched literally.
 */
model: string, inputPerMtok: number, outputPerMtok: number, };
