// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelRate = { model: string, inputPerMtok: number, outputPerMtok: number, 
/**
 * False when neither settings nor the built-in table knows this model.
 */
known: boolean, 
/**
 * True when the rate came from the built-in table rather than settings.
 */
builtIn: boolean, };
