// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateSource } from "./RateSource";

export type ModelRate = { model: string, inputPerMtok: number, outputPerMtok: number, 
/**
 * False when nothing could price this model.
 */
known: boolean, source: RateSource, 
/**
 * What we identified it as and from where, when we had to look it up:
 * "Claude Opus · ~/.claude/trajector-settings.json".
 */
note: string, };
