// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Registry snapshot for the org selector: which orgs are on, which is
 * active, and each org's unread-feed count for dropdown badges.
 */
export type OrgState = { active: string, enabled: Array<string>, unread: Record<string, number>, };
