// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Emitted after every poll cycle so the UI can show connection health.
 */
export type PollStatus = { ok: boolean, message: string | null, at: string, rateLimitRemaining: number, 
/**
 * A poll cycle is in flight right now ("refreshing…" feedback).
 */
syncing: boolean, };
