// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single comment on a PR (conversation or review thread).
 */
export type PrComment = { id: string, author: string, isBot: boolean, body: string, createdAt: string, url: string, };
