// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One commit in a PR's history tab.
 */
export type PrCommit = { sha: string, shortSha: string, 
/**
 * Headline only; full message stays on GitHub.
 */
message: string, author: string, at: string, additions: number, deletions: number, 
/**
 * SUCCESS | FAILURE | ERROR | PENDING | EXPECTED — of this commit's checks.
 */
ciStatus: string | null, url: string, };
