// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrComment } from "./PrComment";
import type { ReviewThread } from "./ReviewThread";
import type { ReviewVerdict } from "./ReviewVerdict";

export type PrConversation = { 
/**
 * Top-level conversation comments, oldest first.
 */
comments: Array<PrComment>, 
/**
 * Code-anchored review threads.
 */
threads: Array<ReviewThread>, 
/**
 * Review verdicts (approve / request changes) with their summary bodies —
 * these live on the review object, not in comments or threads.
 */
reviews: Array<ReviewVerdict>, };
