// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Label } from "./Label";

/**
 * State of a PR as reported by GitHub.
 */
export type PrInfo = { 
/**
 * GraphQL node id — stable across renames/pushes.
 */
id: string, number: number, title: string, url: string, 
/**
 * "owner/name"
 */
repo: string, author: string, isDraft: boolean, 
/**
 * OPEN | MERGED | CLOSED
 */
state: string, 
/**
 * APPROVED | CHANGES_REQUESTED | REVIEW_REQUIRED
 */
reviewDecision: string | null, 
/**
 * SUCCESS | FAILURE | ERROR | PENDING | EXPECTED
 */
ciStatus: string | null, 
/**
 * MERGEABLE | CONFLICTING | UNKNOWN
 */
mergeable: string, additions: number, deletions: number, changedFiles: number, 
/**
 * Issue + review comments; drives the "new comments" attention signal.
 */
totalComments: number, 
/**
 * Logins of the most recent commenters, oldest first; bot accounts are
 * normalized to end in "[bot]" so change detection can skip automation.
 */
recentCommentAuthors: Array<string>, headSha: string, updatedAt: string, labels: Array<Label>, };
