// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-PR attention weighting, set from the PR tree's context menu. Ordered
 * attention-ascending so derived `PartialOrd`/`Ord` compare correctly.
 * `low`/`normal`/`high` are the pre-rename wire names, kept as aliases so
 * old serialized strings still deserialize.
 */
export type PrPriority = "unimportant" | "someday" | "standard" | "important" | "critical";
