// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewSummary } from "./ReviewSummary";

export type PrReviews = { 
/**
 * Logins/teams still requested to review.
 */
requested: Array<string>, 
/**
 * Latest review per reviewer.
 */
reviews: Array<ReviewSummary>, 
/**
 * The PAT owner's login — identifies "my" review.
 */
viewerLogin: string, 
/**
 * When the head commit landed; newer than my review = re-enable actions.
 */
lastCommitAt: string | null, openThreads: number, 
/**
 * Unresolved threads the viewer started — approving over your own open
 * questions is almost always a mistake.
 */
myOpenThreads: number, };
