// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewSummary } from "./ReviewSummary";

export type PrReviews = { 
/**
 * Logins/teams still requested to review.
 */
requested: Array<string>, 
/**
 * Latest review per reviewer.
 */
reviews: Array<ReviewSummary>, };
