// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a rate came from. Ordered by authority: what you set wins over what
 * we inferred, which wins over a name we recognised.
 */
export type RateSource = "yours" | "claude-settings" | "published" | "unknown";
