// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReactionGroup = { 
/**
 * GitHub reaction content: THUMBS_UP, HEART, ROCKET, …
 */
content: string, count: number, viewerHasReacted: boolean, };
