// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecentComment = { id: string, author: string, isBot: boolean, 
/**
 * First ~120 chars, for notification bodies.
 */
snippet: string, };
