// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-repo attention weighting. Ignored repos are never tracked. Ordered
 * attention-ascending so derived `PartialOrd`/`Ord` compare correctly.
 * `low`/`normal`/`high` are the pre-rename wire names, kept as aliases so
 * old serialized strings still deserialize; `ignored` is unchanged.
 */
export type RepoPriority = "ignored" | "unimportant" | "someday" | "standard" | "important" | "critical";
