// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-repo attention weighting. Ignored repos are never tracked.
 */
export type RepoPriority = "high" | "normal" | "low" | "ignored";
