// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who's been asked to review and what reviews exist — shown before analyzing.
 */
export type ReviewSummary = { author: string, 
/**
 * APPROVED | CHANGES_REQUESTED | COMMENTED | DISMISSED | PENDING
 */
state: string, submittedAt: string | null, };
