// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A submitted review's verdict + summary text, shown in the conversation.
 */
export type ReviewVerdict = { id: string, author: string, 
/**
 * APPROVED | CHANGES_REQUESTED | COMMENTED | DISMISSED
 */
state: string, body: string, submittedAt: string, url: string, };
