// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewVerdict } from "./ReviewVerdict";

/**
 * Payload for the `review:submitted` event — the review GitHub just created,
 * carried to the UI because GitHub's own read-back lags the mutation.
 */
export type ReviewSubmittedEvent = { prId: string, verdict: ReviewVerdict, };
