// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One review dismissal from the PR's timeline. GitHub's `latestReviews`
 * drops dismissed reviews entirely, so without this a reviewer whose
 * approval was just dismissed looks like one who never reviewed at all.
 */
export type ReviewDismissal = { at: string, 
/**
 * Who dismissed it: the pusher for an automatic dismissal, the person
 * who clicked Dismiss for a manual one.
 */
actor: string, 
/**
 * Whose review it was.
 */
reviewer: string, 
/**
 * APPROVED | CHANGES_REQUESTED | COMMENTED — what the review said.
 */
previousState: string, 
/**
 * The push that dismissed it under "dismiss stale approvals"; None for
 * a manual dismissal.
 */
commitSha: string | null, commitUrl: string | null, 
/**
 * The reason given for a manual dismissal; empty otherwise.
 */
message: string, };
