// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrComment } from "./PrComment";

/**
 * A review thread anchored to code.
 */
export type ReviewThread = { id: string, path: string | null, line: number | null, startLine: number | null, resolved: boolean, outdated: boolean, comments: Array<PrComment>, };
