// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileMetrics } from "./FileMetrics";
import type { Significance } from "./Significance";

/**
 * Model-assigned per-file review guidance: where to spend attention.
 */
export type ReviewPlanEntry = { path: string, significance: Significance, reason: string, 
/**
 * Computed diff metrics, attached post-hoc (never emitted by the model).
 */
metrics?: FileMetrics, };
