// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Model-assigned per-file review guidance: where to spend attention.
 */
export type ReviewPlanEntry = { path: string, 
/**
 * critical | important | mechanical
 */
significance: string, reason: string, };
