// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the reviewer left off on a PR — the head SHA at their last look.
 */
export type ReviewMark = { headSha: string, at: string, };
