// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisResult } from "./AnalysisResult";
import type { RunStatus } from "./RunStatus";

export type RunRecord = { variantId: string, prId: string, status: RunStatus, startedAt: string, finishedAt: string | null, 
/**
 * Wall clock of the whole run, both passes, queue to result.
 */
elapsedMs: number, inputTokens: number, outputTokens: number, 
/**
 * Dollars from the usage rows the run recorded; None when a model in
 * the run has no rate.
 */
costUsd: number | null, error: string | null, 
/**
 * The result without its trace — the pane compares outcomes, not steps.
 */
result: AnalysisResult | null, };
