// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelPrice } from "./ModelPrice";
import type { RepoPriority } from "./RepoPriority";

export type Settings = { watchedRepos: Array<string>, 
/**
 * "owner/name" → priority; absent means Standard.
 */
repoPriorities: { [key in string]: RepoPriority }, 
/**
 * PR author login → priority; absent means Standard. Ignored authors'
 * PRs (dependabot…) never enter tracking; Important authors' activity is
 * always important.
 */
authorPriorities: { [key in string]: RepoPriority }, pollIntervalSecs: number, 
/**
 * Show the always-on-top callout window when the app starts.
 */
showCalloutOnStartup: boolean, githubGraphqlUrl: string, awsProfile: string, 
/**
 * Explicit region override; some SSO profiles don't carry one.
 */
awsRegion: string, awsEndpointUrl: string, 
/**
 * Bedrock model id — accepts application-inference-profile ARNs.
 */
bedrockModelId: string, 
/**
 * Cheaper/faster model for Component/Code drill-downs; empty = use main.
 */
bedrockDrillModelId: string, 
/**
 * Model for the assistant chat; empty = the drill model (or main when
 * there is no drill model). Chat is interactive and its hard thinking
 * is already in the analysis it is handed, so the faster tier fits.
 */
bedrockChatModelId: string, 
/**
 * Cheap model that pre-reads a diff too large to show the architecture
 * pass whole, clustering files into feature slices so the main model
 * reads the few that matter. Empty disables the scout.
 */
bedrockScoutModelId: string, 
/**
 * Dollars per million tokens, per model id, for the usage dashboard.
 * Inference-profile ARNs name no model, so their rate can only be told
 * to us; recognizable Claude ids fall back to published rates.
 */
modelPrices: Array<ModelPrice>, 
/**
 * Unlocks the Developer settings pane (logs, prompt editing, internals).
 */
developerMode: boolean, 
/**
 * Overrides the analysis system prompt when non-empty.
 */
customSystemPrompt: string, 
/**
 * Glob patterns for insignificant files — auto-skipped in diff review.
 */
reviewIgnoreGlobs: Array<string>, 
/**
 * Pre-warm: auto-run L1 analysis when a PR enters the review queue.
 */
autoAnalyzeReviewRequests: boolean, 
/**
 * Spend guard for pre-warming.
 */
autoAnalyzeDailyCap: number, 
/**
 * Team knowledge no diff reveals — design-system packages, shared
 * libraries, review standards. Injected into analysis and chat prompts.
 */
reviewConventions: string, 
/**
 * Default text to seed the approve composer with; empty falls back to
 * the dynamic per-PR summary. Overridable per repo below.
 */
defaultApproveMessage: string, 
/**
 * "owner/name" → approve-message override, takes precedence over
 * `default_approve_message`.
 */
repoApproveMessages: { [key in string]: string }, 
/**
 * "owner/name" → extra review instructions appended after
 * `review_conventions` for that repo's prompts. Applies to future
 * analysis/chat runs only, not retroactively.
 */
repoReviewInstructions: { [key in string]: string }, 
/**
 * Second analysis stage: line-anchored defect + reuse findings over the
 * review plan's critical/important files.
 */
codeFindingsPass: boolean, 
/**
 * Run the architecture pass on the drill model when the diff metrics
 * say the PR is routine — every file mechanical, or a handful of files
 * with almost no added logic. The summary and review plan of a version
 * bump don't need the top tier.
 */
routeRoutinePrsToDrillModel: boolean, 
/**
 * PRs with no activity inside this window are hidden from the list and
 * excluded from search discovery. 0 disables the filter.
 */
prMaxAgeDays: number, 
/**
 * Poll cadence when this org is NOT the active one in the org selector
 * — background awareness at a gentler rate than the active org.
 */
backgroundPollSecs: number, 
/**
 * Output-token ceiling for the architecture pass (graph + assessment +
 * Well-Architected pillar findings, all in one submission — the large
 * output). A ceiling, not a reservation: costs nothing unless the model
 * generates that many. Raise only as high as your configured Bedrock
 * model's hard output cap allows — set above it and Bedrock errors.
 */
archMaxOutputTokens: number, 
/**
 * Output-token ceiling for the code-level findings pass. Its submission
 * is small; the budget is mostly the model's reasoning before it calls
 * submit_code_findings. Same caveat as the architecture ceiling.
 */
codeMaxOutputTokens: number, 
/**
 * How many activity rows the callout shows — a query cap only. Older
 * rows stay in the local database (kept up to a high runaway guard, not
 * deleted), so shrinking the feed just makes it easier to reach the
 * bottom; it never throws away history.
 */
calloutFeedLimit: number, };
