// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoPriority } from "./RepoPriority";

export type Settings = { watchedRepos: Array<string>, 
/**
 * "owner/name" → priority; absent means Normal.
 */
repoPriorities: { [key in string]: RepoPriority }, pollIntervalSecs: number, 
/**
 * Show the always-on-top callout window when the app starts.
 */
showCalloutOnStartup: boolean, githubGraphqlUrl: string, awsProfile: string, 
/**
 * Explicit region override; some SSO profiles don't carry one.
 */
awsRegion: string, awsEndpointUrl: string, 
/**
 * Bedrock model id — accepts application-inference-profile ARNs.
 */
bedrockModelId: string, 
/**
 * Cheaper/faster model for Component/Code drill-downs; empty = use main.
 */
bedrockDrillModelId: string, 
/**
 * Unlocks the Developer settings pane (logs, prompt editing, internals).
 */
developerMode: boolean, 
/**
 * Overrides the analysis system prompt when non-empty.
 */
customSystemPrompt: string, };
