// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeamsRecipient } from "./TeamsRecipient";

/**
 * What happened to a Teams message: `sent` through the webhook, or
 * `drafted` — Teams opened on the chat with the text in the compose box,
 * one Enter away — when no webhook is configured.
 */
export type TeamsOutcome = { delivery: string, recipient: TeamsRecipient, text: string, };
