// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who a Teams message to a PR's author would go to, and how Cora knows.
 */
export type TeamsRecipient = { login: string, email: string, 
/**
 * directory | directory-name | settings | profile | commits | guessed |
 * personal. The first two are the directory's own answer (a candidate
 * address matched a user; only their display name did — check it); the
 * rest are GitHub-derived fallbacks when the directory can't be asked:
 * the settings override, the profile's public email, the address they
 * commit with, a first.last@ guess from their name, an off-domain
 * address.
 */
source: string, };
