// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who a Teams message to a PR's author would go to, and how Cora knows.
 */
export type TeamsRecipient = { login: string, email: string, 
/**
 * settings | profile | commits | guessed | personal — the settings
 * override; the GitHub profile's public email; the address they author
 * commits with; a first.last@work-domain guess from their display name
 * (check it); or an off-domain address, all that could be found.
 */
source: string, };
