// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One step of the agent's exploration, kept for the activity drawer.
 */
export type TraceStep = { at: string, 
/**
 * "tool" (fetched something) | "thought" (model narration) | "status"
 */
kind: string, message: string, };
