// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeKind } from "./ChangeKind";
import type { Label } from "./Label";
import type { PrPriority } from "./PrPriority";
import type { PrSource } from "./PrSource";
import type { RecentComment } from "./RecentComment";

/**
 * A PR plus Cora-local tracking state. This is what both windows render.
 */
export type TrackedPr = { sources: Array<PrSource>, muted: boolean, priority: PrPriority, 
/**
 * Unacknowledged changes, newest last.
 */
unread: Array<ChangeKind>, firstSeen: string, lastChangeAt: string, 
/**
 * Persistent critical re-assertion state — set elsewhere (poll-time
 * re-derivation), always false at construction here.
 */
needsAttention: boolean, 
/**
 * GraphQL node id — stable across renames/pushes.
 */
id: string, number: number, title: string, 
/**
 * The PR description. Authored intent the diff can't show — what this is
 * for, what was deliberately left out, which ticket it answers to — so
 * the analysis reasons from the author's stated goal, not just the code.
 */
body: string, url: string, 
/**
 * "owner/name"
 */
repo: string, author: string, isDraft: boolean, 
/**
 * OPEN | MERGED | CLOSED
 */
state: string, 
/**
 * APPROVED | CHANGES_REQUESTED | REVIEW_REQUIRED
 */
reviewDecision: string | null, 
/**
 * YOUR latest review's state (APPROVED | CHANGES_REQUESTED | COMMENTED…).
 */
myReviewState: string | null, myReviewedAt: string | null, 
/**
 * Someone re-requested your review after you reviewed — always resurface.
 */
myReviewRerequested: boolean, 
/**
 * SUCCESS | FAILURE | ERROR | PENDING | EXPECTED
 */
ciStatus: string | null, 
/**
 * MERGEABLE | CONFLICTING | UNKNOWN
 */
mergeable: string, additions: number, deletions: number, changedFiles: number, 
/**
 * Issue + review comments; drives the "new comments" attention signal.
 */
totalComments: number, 
/**
 * The most recent comments, oldest first — drives the human-comment
 * attention signal and reply notifications.
 */
recentComments: Array<RecentComment>, headSha: string, updatedAt: string, labels: Array<Label>, };
