// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One recorded request.
 */
export type UsageRow = { at: string, prId: string, repo: string, number: number, prTitle: string, 
/**
 * analysis | code-pass | chat
 */
kind: string, model: string, inputTokens: number, outputTokens: number, cacheRead: number, cacheWrite: number, };
