// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageTotals } from "./UsageTotals";

/**
 * A rollup with a name: one PR, one day, one model, one kind of work.
 */
export type UsageGroup = { key: string, 
/**
 * Human label — a PR title, a date, a model id.
 */
label: string, totals: UsageTotals, };
