// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageTotals = { requests: number, inputTokens: number, outputTokens: number, cacheRead: number, cacheWrite: number, cost: number, 
/**
 * Requests whose model has no rate — their tokens count, their cost doesn't.
 */
unpricedRequests: number, };
