// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRate } from "./ModelRate";
import type { UsageGroup } from "./UsageGroup";
import type { UsageTotals } from "./UsageTotals";

export type UsageStats = { allTime: UsageTotals, last30Days: UsageTotals, 
/**
 * Oldest recorded request, empty when nothing has been recorded.
 */
since: string, 
/**
 * PRs by spend, most expensive first.
 */
byPr: Array<UsageGroup>, byModel: Array<UsageGroup>, byKind: Array<UsageGroup>, 
/**
 * One entry per day with activity, oldest first.
 */
byDay: Array<UsageGroup>, 
/**
 * All-time spend divided by the number of PRs it touched.
 */
costPerPr: number, tokensPerPr: number, prs: number, 
/**
 * What the cached prefix would have cost at full input price, minus what
 * it did cost — the prompt cache's running discount.
 */
cacheSavings: number, 
/**
 * Model ids seen in the data, with the rate in force for each (0 when
 * unpriced). Drives the rate editor.
 */
rates: Array<ModelRate>, };
