// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiConfig } from "./AiConfig";

export type Variant = { id: string, name: string, createdAt: string, config: AiConfig, };
