// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * C4 abstraction levels. L1 covers Context+Container in one pass; deeper
 * levels are generated on demand when the user drills in.
 */
export type AnalysisLevel = "context" | "component" | "code";
