// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisLevel } from "./AnalysisLevel";

/**
 * Streaming progress for the UI ("reading src/payments/…").
 */
export type AnalysisProgress = { prId: string, level: AnalysisLevel, message: string, };
