// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token cost of one analysis run.
 */
export type AnalysisUsage = { inputTokens: number, outputTokens: number, turns: number, };
