// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoundaryImpact } from "./BoundaryImpact";
import type { FitVerdict } from "./FitVerdict";
import type { WaFinding } from "./WaFinding";

export type Assessment = { 
/**
 * What this change *is*, in system terms — 2-4 sentences.
 */
summary: string, fit: FitVerdict, fitRationale: string, 
/**
 * Ordered most-important-first; external impacts always lead.
 */
boundaryImpacts: Array<BoundaryImpact>, wellArchitected: Array<WaFinding>, 
/**
 * What a reviewer without full context needs to know.
 */
contextNotes: Array<string>, };
