// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeStatus } from "./ChangeStatus";

export type C4Edge = { id: string, source: string, target: string, label: string, protocol: string | null, crossesBoundary: boolean, change: ChangeStatus, };
