// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type C4NodeKind = "person" | "external-system" | "system" | "container" | "component" | "code" | "data-store" | "queue";
