// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { C4NodeKind } from "./C4NodeKind";
import type { ChangeStatus } from "./ChangeStatus";

export type C4Node = { 
/**
 * Deterministic id derived from repo/module path so re-analyses don't
 * reshuffle layouts (e.g. "container:api-service").
 */
id: string, name: string, kind: C4NodeKind, technology: string | null, description: string | null, 
/**
 * Parent boundary node id (system a container belongs to, etc.).
 */
boundary: string | null, change: ChangeStatus, };
