// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What changed between two observations of the same PR.
 */
export type ChangeKind = "new" | "ci-changed" | "review-changed" | "new-commits" | "title-changed" | "merged" | "closed" | "reopened" | "draft-changed";
