// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Pillar = "operational-excellence" | "security" | "reliability" | "performance-efficiency" | "cost-optimization" | "sustainability";
