// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeKind } from "./ChangeKind";
import type { TrackedPr } from "./TrackedPr";

/**
 * Payload for the `pr:changed` event.
 */
export type PrChangedEvent = { pr: TrackedPr, changes: Array<ChangeKind>, };
