// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrComment } from "./PrComment";
import type { ReviewThread } from "./ReviewThread";

export type PrConversation = { 
/**
 * Top-level conversation comments, oldest first.
 */
comments: Array<PrComment>, 
/**
 * Code-anchored review threads.
 */
threads: Array<ReviewThread>, };
