// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a PR entered the tracked set. A PR can match several scopes at once.
 */
export type PrSource = "review-requested" | "authored" | "involved" | "watched-repo" | "chat" | "manual";
