// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeKind } from "./ChangeKind";
import type { Label } from "./Label";
import type { PrPriority } from "./PrPriority";
import type { PrSource } from "./PrSource";

/**
 * A PR plus Cora-local tracking state. This is what both windows render.
 */
export type TrackedPr = { sources: Array<PrSource>, muted: boolean, priority: PrPriority, 
/**
 * Unacknowledged changes, newest last.
 */
unread: Array<ChangeKind>, firstSeen: string, lastChangeAt: string, 
/**
 * GraphQL node id — stable across renames/pushes.
 */
id: string, number: number, title: string, url: string, 
/**
 * "owner/name"
 */
repo: string, author: string, isDraft: boolean, 
/**
 * OPEN | MERGED | CLOSED
 */
state: string, 
/**
 * APPROVED | CHANGES_REQUESTED | REVIEW_REQUIRED
 */
reviewDecision: string | null, 
/**
 * SUCCESS | FAILURE | ERROR | PENDING | EXPECTED
 */
ciStatus: string | null, 
/**
 * MERGEABLE | CONFLICTING | UNKNOWN
 */
mergeable: string, additions: number, deletions: number, changedFiles: number, headSha: string, updatedAt: string, labels: Array<Label>, };
