// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pillar } from "./Pillar";
import type { Severity } from "./Severity";

export type WaFinding = { pillar: Pillar, severity: Severity, finding: string, recommendation: string, nodeIds: Array<string>, };
